import nextConfig from "eslint-config-next";

// DESIGN.md §4-5 tokens in app/globals.css are the ONLY colors in this
// codebase (CLAUDE.md hard rule) — this rule catches raw hex literals in
// component code, both plain string literals and hex embedded in template
// literals (e.g. Tailwind arbitrary values like `text-[#2DD4A7]`).
const noRawHexRule = [
  "error",
  {
    selector: "Literal[value=/^#[0-9a-fA-F]{3,8}$/]",
    message:
      "Raw hex colors are forbidden outside app/globals.css — use a DESIGN.md token (var(--token) or a Tailwind utility from the @theme block).",
  },
  {
    selector: "TemplateElement[value.raw=/#[0-9a-fA-F]{3,8}/]",
    message:
      "Raw hex colors are forbidden outside app/globals.css — use a DESIGN.md token (var(--token) or a Tailwind utility from the @theme block).",
  },
];

const eslintConfig = [
  ...nextConfig,
  {
    ignores: [".next/**", "node_modules/**", "playwright-report/**"],
  },
  {
    files: ["**/*.{ts,tsx}"],
    // shadcn-generated primitives are CSS-var driven by construction and
    // regenerated by `shadcn add`, not hand-authored — excluded so a rare
    // upstream hex literal doesn't block unrelated work; call out any
    // exclusion hit in PR review rather than silently loosening the rule.
    ignores: ["components/ui/**"],
    rules: {
      "no-restricted-syntax": noRawHexRule,
    },
  },
];

export default eslintConfig;
