// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alerts.sql

package db

import (
	"context"
)

const claimPendingAlerts = `-- name: ClaimPendingAlerts :many
SELECT id, monitor_id, event_id, channel, status, attempts, next_attempt_at, sent_at, created_at FROM alerts
WHERE next_attempt_at < now()
  AND status = 'pending'
ORDER BY next_attempt_at
LIMIT $1
FOR UPDATE SKIP LOCKED
`

// Worker scan #3: alerter claims pending outbox rows ready for (re)send.
// Uses idx_alerts_pending (next_attempt_at, partial WHERE status = 'pending').
func (q *Queries) ClaimPendingAlerts(ctx context.Context, limit int32) ([]Alert, error) {
	rows, err := q.db.Query(ctx, claimPendingAlerts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Alert{}
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.MonitorID,
			&i.EventID,
			&i.Channel,
			&i.Status,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.SentAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
