// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checkins.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertCheckin = `-- name: InsertCheckin :one
INSERT INTO checkins (monitor_id, kind, source_ip, user_agent, body)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, monitor_id, kind, source_ip, user_agent, body, created_at
`

type InsertCheckinParams struct {
	MonitorID pgtype.UUID `json:"monitor_id"`
	Kind      string      `json:"kind"`
	SourceIp  *netip.Addr `json:"source_ip"`
	UserAgent pgtype.Text `json:"user_agent"`
	Body      pgtype.Text `json:"body"`
}

// Ingest fast path (PING-008): every ping records exactly one checkin row.
// source_ip (INET) / user_agent / body are nullable; the store passes NULL
// when absent. body is already truncated to 10 KB by the server handler.
func (q *Queries) InsertCheckin(ctx context.Context, arg InsertCheckinParams) (Checkin, error) {
	row := q.db.QueryRow(ctx, insertCheckin,
		arg.MonitorID,
		arg.Kind,
		arg.SourceIp,
		arg.UserAgent,
		arg.Body,
	)
	var i Checkin
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.Kind,
		&i.SourceIp,
		&i.UserAgent,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}
