// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: daily_stats.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listDailyStatsByMonitorIDs = `-- name: ListDailyStatsByMonitorIDs :many
SELECT monitor_id, day, checkins, failures, downtime_s, latency_p50, latency_p95 FROM daily_stats
WHERE monitor_id = ANY($1::uuid[])
  AND day >= $2::date
ORDER BY monitor_id, day ASC
`

type ListDailyStatsByMonitorIDsParams struct {
	MonitorIds []pgtype.UUID `json:"monitor_ids"`
	Since      pgtype.Date   `json:"since"`
}

// Dashboard uptime bar (PING-013): last-N-days rollups for a batch of
// monitors in one query (avoids N+1 across a list page). Table is written by
// the nightly rollup job (PING-020, not yet built) — until then this always
// returns zero rows, which callers must treat as "no data yet", not an error.
func (q *Queries) ListDailyStatsByMonitorIDs(ctx context.Context, arg ListDailyStatsByMonitorIDsParams) ([]DailyStat, error) {
	rows, err := q.db.Query(ctx, listDailyStatsByMonitorIDs, arg.MonitorIds, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailyStat{}
	for rows.Next() {
		var i DailyStat
		if err := rows.Scan(
			&i.MonitorID,
			&i.Day,
			&i.Checkins,
			&i.Failures,
			&i.DowntimeS,
			&i.LatencyP50,
			&i.LatencyP95,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
