// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertEvent = `-- name: InsertEvent :one
INSERT INTO events (monitor_id, type, message, meta)
VALUES ($1, $2, $3, COALESCE($4::jsonb, '{}'::jsonb))
RETURNING id, monitor_id, type, message, meta, created_at
`

type InsertEventParams struct {
	MonitorID pgtype.UUID `json:"monitor_id"`
	Type      string      `json:"type"`
	Message   string      `json:"message"`
	Meta      []byte      `json:"meta"`
}

// Timeline events for a monitor (state transitions, config changes, etc.).
// meta defaults to an empty object when the caller passes NULL.
func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, insertEvent,
		arg.MonitorID,
		arg.Type,
		arg.Message,
		arg.Meta,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.Type,
		&i.Message,
		&i.Meta,
		&i.CreatedAt,
	)
	return i, err
}
