// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Alert struct {
	ID            int64              `json:"id"`
	MonitorID     pgtype.UUID        `json:"monitor_id"`
	EventID       int64              `json:"event_id"`
	Channel       string             `json:"channel"`
	Status        string             `json:"status"`
	Attempts      int32              `json:"attempts"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	SentAt        pgtype.Timestamptz `json:"sent_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type ApiKey struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	KeyHash    string             `json:"key_hash"`
	Label      string             `json:"label"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Checkin struct {
	ID        int64              `json:"id"`
	MonitorID pgtype.UUID        `json:"monitor_id"`
	Kind      string             `json:"kind"`
	SourceIp  *netip.Addr        `json:"source_ip"`
	UserAgent pgtype.Text        `json:"user_agent"`
	Body      pgtype.Text        `json:"body"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type DailyStat struct {
	MonitorID  pgtype.UUID `json:"monitor_id"`
	Day        pgtype.Date `json:"day"`
	Checkins   int32       `json:"checkins"`
	Failures   int32       `json:"failures"`
	DowntimeS  int32       `json:"downtime_s"`
	LatencyP50 pgtype.Int4 `json:"latency_p50"`
	LatencyP95 pgtype.Int4 `json:"latency_p95"`
}

type Event struct {
	ID        int64              `json:"id"`
	MonitorID pgtype.UUID        `json:"monitor_id"`
	Type      string             `json:"type"`
	Message   string             `json:"message"`
	Meta      []byte             `json:"meta"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Monitor struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	Kind          string             `json:"kind"`
	Slug          string             `json:"slug"`
	Name          string             `json:"name"`
	ScheduleKind  pgtype.Text        `json:"schedule_kind"`
	PeriodS       pgtype.Int4        `json:"period_s"`
	CronExpr      pgtype.Text        `json:"cron_expr"`
	Tz            string             `json:"tz"`
	GraceS        pgtype.Int4        `json:"grace_s"`
	Url           pgtype.Text        `json:"url"`
	Method        pgtype.Text        `json:"method"`
	IntervalS     pgtype.Int4        `json:"interval_s"`
	TimeoutS      pgtype.Int4        `json:"timeout_s"`
	FailThreshold pgtype.Int4        `json:"fail_threshold"`
	HttpConfig    []byte             `json:"http_config"`
	State         string             `json:"state"`
	FailStreak    int32              `json:"fail_streak"`
	LastCheckinAt pgtype.Timestamptz `json:"last_checkin_at"`
	NextDeadline  pgtype.Timestamptz `json:"next_deadline"`
	NextProbeAt   pgtype.Timestamptz `json:"next_probe_at"`
	AlertsMuted   bool               `json:"alerts_muted"`
	PausedAt      pgtype.Timestamptz `json:"paused_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type ProbeResult struct {
	ID           int64              `json:"id"`
	MonitorID    pgtype.UUID        `json:"monitor_id"`
	Ok           bool               `json:"ok"`
	HttpStatus   pgtype.Int4        `json:"http_status"`
	LatencyMs    pgtype.Int4        `json:"latency_ms"`
	Error        pgtype.Text        `json:"error"`
	TlsExpiresAt pgtype.Timestamptz `json:"tls_expires_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
