// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: monitors.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimDueMonitors = `-- name: ClaimDueMonitors :many
SELECT id, user_id, kind, slug, name, schedule_kind, period_s, cron_expr, tz, grace_s, url, method, interval_s, timeout_s, fail_threshold, http_config, state, fail_streak, last_checkin_at, next_deadline, next_probe_at, alerts_muted, paused_at, created_at, updated_at, auto_resume, reminder_every_s FROM monitors
WHERE next_deadline < $1
  AND state IN ('up', 'late')
  AND paused_at IS NULL
ORDER BY next_deadline
LIMIT $2
FOR UPDATE SKIP LOCKED
`

type ClaimDueMonitorsParams struct {
	Now       pgtype.Timestamptz `json:"now"`
	PageLimit int32              `json:"page_limit"`
}

// Worker scan #1: scheduler claims heartbeat monitors past their deadline.
// Uses idx_monitors_due (next_deadline, partial WHERE state IN ('up','late') AND paused_at IS NULL).
// The evaluation clock is passed in (sqlc.arg(now)) rather than SQL now() so the
// claim and the in-Go transition math share one consistent instant, and tests
// can drive it deterministically. Production passes time.Now().
func (q *Queries) ClaimDueMonitors(ctx context.Context, arg ClaimDueMonitorsParams) ([]Monitor, error) {
	rows, err := q.db.Query(ctx, claimDueMonitors, arg.Now, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Monitor{}
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.Slug,
			&i.Name,
			&i.ScheduleKind,
			&i.PeriodS,
			&i.CronExpr,
			&i.Tz,
			&i.GraceS,
			&i.Url,
			&i.Method,
			&i.IntervalS,
			&i.TimeoutS,
			&i.FailThreshold,
			&i.HttpConfig,
			&i.State,
			&i.FailStreak,
			&i.LastCheckinAt,
			&i.NextDeadline,
			&i.NextProbeAt,
			&i.AlertsMuted,
			&i.PausedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AutoResume,
			&i.ReminderEveryS,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimDueProbes = `-- name: ClaimDueProbes :many
SELECT id, user_id, kind, slug, name, schedule_kind, period_s, cron_expr, tz, grace_s, url, method, interval_s, timeout_s, fail_threshold, http_config, state, fail_streak, last_checkin_at, next_deadline, next_probe_at, alerts_muted, paused_at, created_at, updated_at, auto_resume, reminder_every_s FROM monitors
WHERE next_probe_at < now()
  AND kind = 'http'
  AND paused_at IS NULL
ORDER BY next_probe_at
LIMIT $1
FOR UPDATE SKIP LOCKED
`

// Worker scan #2: prober claims http monitors due for their next probe.
// Uses idx_monitors_probe_due (next_probe_at, partial WHERE kind = 'http' AND paused_at IS NULL).
func (q *Queries) ClaimDueProbes(ctx context.Context, limit int32) ([]Monitor, error) {
	rows, err := q.db.Query(ctx, claimDueProbes, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Monitor{}
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.Slug,
			&i.Name,
			&i.ScheduleKind,
			&i.PeriodS,
			&i.CronExpr,
			&i.Tz,
			&i.GraceS,
			&i.Url,
			&i.Method,
			&i.IntervalS,
			&i.TimeoutS,
			&i.FailThreshold,
			&i.HttpConfig,
			&i.State,
			&i.FailStreak,
			&i.LastCheckinAt,
			&i.NextDeadline,
			&i.NextProbeAt,
			&i.AlertsMuted,
			&i.PausedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AutoResume,
			&i.ReminderEveryS,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createMonitor = `-- name: CreateMonitor :one
INSERT INTO monitors (
    user_id, kind, slug, name,
    schedule_kind, period_s, cron_expr, tz, grace_s,
    url, method, interval_s, timeout_s, fail_threshold, http_config,
    auto_resume
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    COALESCE(NULLIF($8::text, ''), 'UTC'), $9,
    $10, $11, $12, $13, $14,
    COALESCE($15::jsonb, '{}'::jsonb),
    COALESCE($16::boolean, true)
)
RETURNING id, user_id, kind, slug, name, schedule_kind, period_s, cron_expr, tz, grace_s, url, method, interval_s, timeout_s, fail_threshold, http_config, state, fail_streak, last_checkin_at, next_deadline, next_probe_at, alerts_muted, paused_at, created_at, updated_at, auto_resume, reminder_every_s
`

type CreateMonitorParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	Kind          string      `json:"kind"`
	Slug          string      `json:"slug"`
	Name          string      `json:"name"`
	ScheduleKind  pgtype.Text `json:"schedule_kind"`
	PeriodS       pgtype.Int4 `json:"period_s"`
	CronExpr      pgtype.Text `json:"cron_expr"`
	Tz            string      `json:"tz"`
	GraceS        pgtype.Int4 `json:"grace_s"`
	Url           pgtype.Text `json:"url"`
	Method        pgtype.Text `json:"method"`
	IntervalS     pgtype.Int4 `json:"interval_s"`
	TimeoutS      pgtype.Int4 `json:"timeout_s"`
	FailThreshold pgtype.Int4 `json:"fail_threshold"`
	HttpConfig    []byte      `json:"http_config"`
	AutoResume    pgtype.Bool `json:"auto_resume"`
}

func (q *Queries) CreateMonitor(ctx context.Context, arg CreateMonitorParams) (Monitor, error) {
	row := q.db.QueryRow(ctx, createMonitor,
		arg.UserID,
		arg.Kind,
		arg.Slug,
		arg.Name,
		arg.ScheduleKind,
		arg.PeriodS,
		arg.CronExpr,
		arg.Tz,
		arg.GraceS,
		arg.Url,
		arg.Method,
		arg.IntervalS,
		arg.TimeoutS,
		arg.FailThreshold,
		arg.HttpConfig,
		arg.AutoResume,
	)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Slug,
		&i.Name,
		&i.ScheduleKind,
		&i.PeriodS,
		&i.CronExpr,
		&i.Tz,
		&i.GraceS,
		&i.Url,
		&i.Method,
		&i.IntervalS,
		&i.TimeoutS,
		&i.FailThreshold,
		&i.HttpConfig,
		&i.State,
		&i.FailStreak,
		&i.LastCheckinAt,
		&i.NextDeadline,
		&i.NextProbeAt,
		&i.AlertsMuted,
		&i.PausedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AutoResume,
		&i.ReminderEveryS,
	)
	return i, err
}

const deleteMonitor = `-- name: DeleteMonitor :execrows
DELETE FROM monitors
WHERE id = $1 AND user_id = $2
`

type DeleteMonitorParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

// :execrows (not :exec) so the store layer can tell "deleted" apart from
// "no matching row" (foreign or already-deleted id) via RowsAffected.
func (q *Queries) DeleteMonitor(ctx context.Context, arg DeleteMonitorParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMonitor, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMonitorByID = `-- name: GetMonitorByID :one
SELECT id, user_id, kind, slug, name, schedule_kind, period_s, cron_expr, tz, grace_s, url, method, interval_s, timeout_s, fail_threshold, http_config, state, fail_streak, last_checkin_at, next_deadline, next_probe_at, alerts_muted, paused_at, created_at, updated_at, auto_resume, reminder_every_s FROM monitors
WHERE id = $1
`

func (q *Queries) GetMonitorByID(ctx context.Context, id pgtype.UUID) (Monitor, error) {
	row := q.db.QueryRow(ctx, getMonitorByID, id)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Slug,
		&i.Name,
		&i.ScheduleKind,
		&i.PeriodS,
		&i.CronExpr,
		&i.Tz,
		&i.GraceS,
		&i.Url,
		&i.Method,
		&i.IntervalS,
		&i.TimeoutS,
		&i.FailThreshold,
		&i.HttpConfig,
		&i.State,
		&i.FailStreak,
		&i.LastCheckinAt,
		&i.NextDeadline,
		&i.NextProbeAt,
		&i.AlertsMuted,
		&i.PausedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AutoResume,
		&i.ReminderEveryS,
	)
	return i, err
}

const getMonitorBySlug = `-- name: GetMonitorBySlug :one
SELECT id, user_id, kind, slug, name, schedule_kind, period_s, cron_expr, tz, grace_s, url, method, interval_s, timeout_s, fail_threshold, http_config, state, fail_streak, last_checkin_at, next_deadline, next_probe_at, alerts_muted, paused_at, created_at, updated_at, auto_resume, reminder_every_s FROM monitors
WHERE slug = $1
`

func (q *Queries) GetMonitorBySlug(ctx context.Context, slug string) (Monitor, error) {
	row := q.db.QueryRow(ctx, getMonitorBySlug, slug)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Slug,
		&i.Name,
		&i.ScheduleKind,
		&i.PeriodS,
		&i.CronExpr,
		&i.Tz,
		&i.GraceS,
		&i.Url,
		&i.Method,
		&i.IntervalS,
		&i.TimeoutS,
		&i.FailThreshold,
		&i.HttpConfig,
		&i.State,
		&i.FailStreak,
		&i.LastCheckinAt,
		&i.NextDeadline,
		&i.NextProbeAt,
		&i.AlertsMuted,
		&i.PausedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AutoResume,
		&i.ReminderEveryS,
	)
	return i, err
}

const getMonitorBySlugForUpdate = `-- name: GetMonitorBySlugForUpdate :one
SELECT id, user_id, kind, slug, name, schedule_kind, period_s, cron_expr, tz, grace_s, url, method, interval_s, timeout_s, fail_threshold, http_config, state, fail_streak, last_checkin_at, next_deadline, next_probe_at, alerts_muted, paused_at, created_at, updated_at, auto_resume, reminder_every_s FROM monitors
WHERE slug = $1
FOR UPDATE
`

// Ingest fast path (PING-008): fetch the monitor and lock its row for the rest
// of the transaction. Plain FOR UPDATE (block, don't skip) — every ping must be
// processed, and the lock serializes concurrent pings on the same slug so the
// read-state / transition / write is atomic (no duplicate recovery/down rows).
func (q *Queries) GetMonitorBySlugForUpdate(ctx context.Context, slug string) (Monitor, error) {
	row := q.db.QueryRow(ctx, getMonitorBySlugForUpdate, slug)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Slug,
		&i.Name,
		&i.ScheduleKind,
		&i.PeriodS,
		&i.CronExpr,
		&i.Tz,
		&i.GraceS,
		&i.Url,
		&i.Method,
		&i.IntervalS,
		&i.TimeoutS,
		&i.FailThreshold,
		&i.HttpConfig,
		&i.State,
		&i.FailStreak,
		&i.LastCheckinAt,
		&i.NextDeadline,
		&i.NextProbeAt,
		&i.AlertsMuted,
		&i.PausedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AutoResume,
		&i.ReminderEveryS,
	)
	return i, err
}

const listMonitorsByUser = `-- name: ListMonitorsByUser :many
SELECT id, user_id, kind, slug, name, schedule_kind, period_s, cron_expr, tz, grace_s, url, method, interval_s, timeout_s, fail_threshold, http_config, state, fail_streak, last_checkin_at, next_deadline, next_probe_at, alerts_muted, paused_at, created_at, updated_at, auto_resume, reminder_every_s FROM monitors
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListMonitorsByUser(ctx context.Context, userID pgtype.UUID) ([]Monitor, error) {
	rows, err := q.db.Query(ctx, listMonitorsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Monitor{}
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.Slug,
			&i.Name,
			&i.ScheduleKind,
			&i.PeriodS,
			&i.CronExpr,
			&i.Tz,
			&i.GraceS,
			&i.Url,
			&i.Method,
			&i.IntervalS,
			&i.TimeoutS,
			&i.FailThreshold,
			&i.HttpConfig,
			&i.State,
			&i.FailStreak,
			&i.LastCheckinAt,
			&i.NextDeadline,
			&i.NextProbeAt,
			&i.AlertsMuted,
			&i.PausedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AutoResume,
			&i.ReminderEveryS,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonitorsByUserPage = `-- name: ListMonitorsByUserPage :many
SELECT id, user_id, kind, slug, name, schedule_kind, period_s, cron_expr, tz, grace_s, url, method, interval_s, timeout_s, fail_threshold, http_config, state, fail_streak, last_checkin_at, next_deadline, next_probe_at, alerts_muted, paused_at, created_at, updated_at, auto_resume, reminder_every_s FROM monitors
WHERE user_id = $1
  AND (
    $2::timestamptz IS NULL
    OR (created_at, id) < ($2::timestamptz, $3::uuid)
  )
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListMonitorsByUserPageParams struct {
	UserID          pgtype.UUID        `json:"user_id"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	PageLimit       int32              `json:"page_limit"`
}

// Cursor pagination on (created_at, id) rather than OFFSET: created_at alone
// isn't unique, so the composite key keeps page boundaries stable under
// concurrent inserts. sqlc.narg(cursor_created_at)/sqlc.narg(cursor_id) are
// both NULL on the first page (no WHERE filter applied).
func (q *Queries) ListMonitorsByUserPage(ctx context.Context, arg ListMonitorsByUserPageParams) ([]Monitor, error) {
	rows, err := q.db.Query(ctx, listMonitorsByUserPage,
		arg.UserID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Monitor{}
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.Slug,
			&i.Name,
			&i.ScheduleKind,
			&i.PeriodS,
			&i.CronExpr,
			&i.Tz,
			&i.GraceS,
			&i.Url,
			&i.Method,
			&i.IntervalS,
			&i.TimeoutS,
			&i.FailThreshold,
			&i.HttpConfig,
			&i.State,
			&i.FailStreak,
			&i.LastCheckinAt,
			&i.NextDeadline,
			&i.NextProbeAt,
			&i.AlertsMuted,
			&i.PausedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AutoResume,
			&i.ReminderEveryS,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMonitorDown = `-- name: MarkMonitorDown :exec
UPDATE monitors
SET state         = 'down',
    next_deadline = NULL,
    fail_streak   = fail_streak + 1,
    updated_at    = now()
WHERE id = $1
`

// Scheduler late->down (PING-009): clear the deadline and bump the fail streak.
// paused_at untouched (see MarkMonitorLate).
func (q *Queries) MarkMonitorDown(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markMonitorDown, id)
	return err
}

const markMonitorLate = `-- name: MarkMonitorLate :exec
UPDATE monitors
SET state         = 'late',
    next_deadline = $1,
    updated_at    = now()
WHERE id = $2
`

type MarkMonitorLateParams struct {
	NextDeadline pgtype.Timestamptz `json:"next_deadline"`
	ID           pgtype.UUID        `json:"id"`
}

// Scheduler up->late (PING-009): re-arm next_deadline to the DOWN threshold
// (occurrence + grace, computed by the caller) and flip state. paused_at is
// deliberately untouched — the scheduler must never resume a paused monitor
// (unlike UpdateMonitorOnCheckin, which auto-resumes on a real check-in).
func (q *Queries) MarkMonitorLate(ctx context.Context, arg MarkMonitorLateParams) error {
	_, err := q.db.Exec(ctx, markMonitorLate, arg.NextDeadline, arg.ID)
	return err
}

const muteMonitor = `-- name: MuteMonitor :one
UPDATE monitors
SET alerts_muted = true, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, kind, slug, name, schedule_kind, period_s, cron_expr, tz, grace_s, url, method, interval_s, timeout_s, fail_threshold, http_config, state, fail_streak, last_checkin_at, next_deadline, next_probe_at, alerts_muted, paused_at, created_at, updated_at, auto_resume, reminder_every_s
`

type MuteMonitorParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) MuteMonitor(ctx context.Context, arg MuteMonitorParams) (Monitor, error) {
	row := q.db.QueryRow(ctx, muteMonitor, arg.ID, arg.UserID)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Slug,
		&i.Name,
		&i.ScheduleKind,
		&i.PeriodS,
		&i.CronExpr,
		&i.Tz,
		&i.GraceS,
		&i.Url,
		&i.Method,
		&i.IntervalS,
		&i.TimeoutS,
		&i.FailThreshold,
		&i.HttpConfig,
		&i.State,
		&i.FailStreak,
		&i.LastCheckinAt,
		&i.NextDeadline,
		&i.NextProbeAt,
		&i.AlertsMuted,
		&i.PausedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AutoResume,
		&i.ReminderEveryS,
	)
	return i, err
}

const pauseMonitor = `-- name: PauseMonitor :one
UPDATE monitors
SET paused_at = now(), updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, kind, slug, name, schedule_kind, period_s, cron_expr, tz, grace_s, url, method, interval_s, timeout_s, fail_threshold, http_config, state, fail_streak, last_checkin_at, next_deadline, next_probe_at, alerts_muted, paused_at, created_at, updated_at, auto_resume, reminder_every_s
`

type PauseMonitorParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

// Pause (PING-010): set the flag only — state is deliberately untouched (paused
// is a flag, not a state, per §2.3). RETURNING so the handler can echo the
// updated monitor. Zero rows affected (foreign/missing id) => ErrNotFound.
func (q *Queries) PauseMonitor(ctx context.Context, arg PauseMonitorParams) (Monitor, error) {
	row := q.db.QueryRow(ctx, pauseMonitor, arg.ID, arg.UserID)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Slug,
		&i.Name,
		&i.ScheduleKind,
		&i.PeriodS,
		&i.CronExpr,
		&i.Tz,
		&i.GraceS,
		&i.Url,
		&i.Method,
		&i.IntervalS,
		&i.TimeoutS,
		&i.FailThreshold,
		&i.HttpConfig,
		&i.State,
		&i.FailStreak,
		&i.LastCheckinAt,
		&i.NextDeadline,
		&i.NextProbeAt,
		&i.AlertsMuted,
		&i.PausedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AutoResume,
		&i.ReminderEveryS,
	)
	return i, err
}

const resumeMonitor = `-- name: ResumeMonitor :one
UPDATE monitors
SET paused_at     = NULL,
    state         = 'up',
    next_deadline = $1,
    updated_at    = now()
WHERE id = $2 AND user_id = $3
RETURNING id, user_id, kind, slug, name, schedule_kind, period_s, cron_expr, tz, grace_s, url, method, interval_s, timeout_s, fail_threshold, http_config, state, fail_streak, last_checkin_at, next_deadline, next_probe_at, alerts_muted, paused_at, created_at, updated_at, auto_resume, reminder_every_s
`

type ResumeMonitorParams struct {
	NextDeadline pgtype.Timestamptz `json:"next_deadline"`
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
}

// Resume (PING-010): a clean restart — clear the flag, set state='up', and
// re-arm next_deadline from the resume moment (computed by the caller via
// nextDeadlineFor; NULL for non-heartbeat / unscheduled). Re-arming from now is
// what stops a monitor paused past its deadline from tripping late/down the
// instant it resumes (AC-2).
func (q *Queries) ResumeMonitor(ctx context.Context, arg ResumeMonitorParams) (Monitor, error) {
	row := q.db.QueryRow(ctx, resumeMonitor, arg.NextDeadline, arg.ID, arg.UserID)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Slug,
		&i.Name,
		&i.ScheduleKind,
		&i.PeriodS,
		&i.CronExpr,
		&i.Tz,
		&i.GraceS,
		&i.Url,
		&i.Method,
		&i.IntervalS,
		&i.TimeoutS,
		&i.FailThreshold,
		&i.HttpConfig,
		&i.State,
		&i.FailStreak,
		&i.LastCheckinAt,
		&i.NextDeadline,
		&i.NextProbeAt,
		&i.AlertsMuted,
		&i.PausedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AutoResume,
		&i.ReminderEveryS,
	)
	return i, err
}

const unmuteMonitor = `-- name: UnmuteMonitor :one
UPDATE monitors
SET alerts_muted = false, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, kind, slug, name, schedule_kind, period_s, cron_expr, tz, grace_s, url, method, interval_s, timeout_s, fail_threshold, http_config, state, fail_streak, last_checkin_at, next_deadline, next_probe_at, alerts_muted, paused_at, created_at, updated_at, auto_resume, reminder_every_s
`

type UnmuteMonitorParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) UnmuteMonitor(ctx context.Context, arg UnmuteMonitorParams) (Monitor, error) {
	row := q.db.QueryRow(ctx, unmuteMonitor, arg.ID, arg.UserID)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Slug,
		&i.Name,
		&i.ScheduleKind,
		&i.PeriodS,
		&i.CronExpr,
		&i.Tz,
		&i.GraceS,
		&i.Url,
		&i.Method,
		&i.IntervalS,
		&i.TimeoutS,
		&i.FailThreshold,
		&i.HttpConfig,
		&i.State,
		&i.FailStreak,
		&i.LastCheckinAt,
		&i.NextDeadline,
		&i.NextProbeAt,
		&i.AlertsMuted,
		&i.PausedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AutoResume,
		&i.ReminderEveryS,
	)
	return i, err
}

const updateMonitor = `-- name: UpdateMonitor :one
UPDATE monitors
SET
    name           = COALESCE($1, name),
    schedule_kind  = COALESCE($2, schedule_kind),
    period_s       = COALESCE($3, period_s),
    cron_expr      = COALESCE($4, cron_expr),
    tz             = COALESCE($5, tz),
    grace_s        = COALESCE($6, grace_s),
    url            = COALESCE($7, url),
    method         = COALESCE($8, method),
    interval_s     = COALESCE($9, interval_s),
    timeout_s      = COALESCE($10, timeout_s),
    fail_threshold = COALESCE($11, fail_threshold),
    http_config    = COALESCE($12::jsonb, http_config),
    auto_resume    = COALESCE($13::boolean, auto_resume),
    updated_at     = now()
WHERE id = $14 AND user_id = $15
RETURNING id, user_id, kind, slug, name, schedule_kind, period_s, cron_expr, tz, grace_s, url, method, interval_s, timeout_s, fail_threshold, http_config, state, fail_streak, last_checkin_at, next_deadline, next_probe_at, alerts_muted, paused_at, created_at, updated_at, auto_resume, reminder_every_s
`

type UpdateMonitorParams struct {
	Name          pgtype.Text `json:"name"`
	ScheduleKind  pgtype.Text `json:"schedule_kind"`
	PeriodS       pgtype.Int4 `json:"period_s"`
	CronExpr      pgtype.Text `json:"cron_expr"`
	Tz            pgtype.Text `json:"tz"`
	GraceS        pgtype.Int4 `json:"grace_s"`
	Url           pgtype.Text `json:"url"`
	Method        pgtype.Text `json:"method"`
	IntervalS     pgtype.Int4 `json:"interval_s"`
	TimeoutS      pgtype.Int4 `json:"timeout_s"`
	FailThreshold pgtype.Int4 `json:"fail_threshold"`
	HttpConfig    []byte      `json:"http_config"`
	AutoResume    pgtype.Bool `json:"auto_resume"`
	ID            pgtype.UUID `json:"id"`
	UserID        pgtype.UUID `json:"user_id"`
}

// Partial update: sqlc.narg fields left NULL keep their current value via
// COALESCE. Ownership-enforced by the id + user_id WHERE, matching
// Pause/Resume/Delete — a foreign monitor_id updates zero rows rather than
// erroring, so the store layer must check RowsAffected/pgx.ErrNoRows.
func (q *Queries) UpdateMonitor(ctx context.Context, arg UpdateMonitorParams) (Monitor, error) {
	row := q.db.QueryRow(ctx, updateMonitor,
		arg.Name,
		arg.ScheduleKind,
		arg.PeriodS,
		arg.CronExpr,
		arg.Tz,
		arg.GraceS,
		arg.Url,
		arg.Method,
		arg.IntervalS,
		arg.TimeoutS,
		arg.FailThreshold,
		arg.HttpConfig,
		arg.AutoResume,
		arg.ID,
		arg.UserID,
	)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Slug,
		&i.Name,
		&i.ScheduleKind,
		&i.PeriodS,
		&i.CronExpr,
		&i.Tz,
		&i.GraceS,
		&i.Url,
		&i.Method,
		&i.IntervalS,
		&i.TimeoutS,
		&i.FailThreshold,
		&i.HttpConfig,
		&i.State,
		&i.FailStreak,
		&i.LastCheckinAt,
		&i.NextDeadline,
		&i.NextProbeAt,
		&i.AlertsMuted,
		&i.PausedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AutoResume,
		&i.ReminderEveryS,
	)
	return i, err
}

const updateMonitorOnCheckin = `-- name: UpdateMonitorOnCheckin :exec
UPDATE monitors
SET state           = $1,
    last_checkin_at = $2,
    next_deadline   = $3,
    fail_streak     = $4,
    paused_at       = CASE WHEN auto_resume THEN NULL ELSE paused_at END,
    updated_at      = now()
WHERE id = $5
`

type UpdateMonitorOnCheckinParams struct {
	State         string             `json:"state"`
	LastCheckinAt pgtype.Timestamptz `json:"last_checkin_at"`
	NextDeadline  pgtype.Timestamptz `json:"next_deadline"`
	FailStreak    int32              `json:"fail_streak"`
	ID            pgtype.UUID        `json:"id"`
}

// Ingest fast path (PING-008): apply a check-in's effect to the monitor row we
// already hold locked via GetMonitorBySlugForUpdate. next_deadline is NULL on a
// fail; paused_at is always cleared (any check-in auto-resumes the monitor).
// paused_at is cleared (auto-resume) only when the monitor's auto_resume flag is
// set (PING-010). With auto_resume=false a check-in still records state and
// re-arms next_deadline, but leaves paused_at set — the scheduler keeps skipping
// it (its claims filter paused_at IS NULL), so the future deadline is inert
// until the monitor is explicitly resumed.
func (q *Queries) UpdateMonitorOnCheckin(ctx context.Context, arg UpdateMonitorOnCheckinParams) error {
	_, err := q.db.Exec(ctx, updateMonitorOnCheckin,
		arg.State,
		arg.LastCheckinAt,
		arg.NextDeadline,
		arg.FailStreak,
		arg.ID,
	)
	return err
}
