// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: monitors.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimDueMonitors = `-- name: ClaimDueMonitors :many
SELECT id, user_id, kind, slug, name, schedule_kind, period_s, cron_expr, tz, grace_s, url, method, interval_s, timeout_s, fail_threshold, http_config, state, fail_streak, last_checkin_at, next_deadline, next_probe_at, alerts_muted, paused_at, created_at, updated_at FROM monitors
WHERE next_deadline < now()
  AND state IN ('up', 'late')
  AND paused_at IS NULL
ORDER BY next_deadline
LIMIT $1
FOR UPDATE SKIP LOCKED
`

// Worker scan #1: scheduler claims heartbeat monitors past their deadline.
// Uses idx_monitors_due (next_deadline, partial WHERE state IN ('up','late') AND paused_at IS NULL).
func (q *Queries) ClaimDueMonitors(ctx context.Context, limit int32) ([]Monitor, error) {
	rows, err := q.db.Query(ctx, claimDueMonitors, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Monitor{}
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.Slug,
			&i.Name,
			&i.ScheduleKind,
			&i.PeriodS,
			&i.CronExpr,
			&i.Tz,
			&i.GraceS,
			&i.Url,
			&i.Method,
			&i.IntervalS,
			&i.TimeoutS,
			&i.FailThreshold,
			&i.HttpConfig,
			&i.State,
			&i.FailStreak,
			&i.LastCheckinAt,
			&i.NextDeadline,
			&i.NextProbeAt,
			&i.AlertsMuted,
			&i.PausedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimDueProbes = `-- name: ClaimDueProbes :many
SELECT id, user_id, kind, slug, name, schedule_kind, period_s, cron_expr, tz, grace_s, url, method, interval_s, timeout_s, fail_threshold, http_config, state, fail_streak, last_checkin_at, next_deadline, next_probe_at, alerts_muted, paused_at, created_at, updated_at FROM monitors
WHERE next_probe_at < now()
  AND kind = 'http'
  AND paused_at IS NULL
ORDER BY next_probe_at
LIMIT $1
FOR UPDATE SKIP LOCKED
`

// Worker scan #2: prober claims http monitors due for their next probe.
// Uses idx_monitors_probe_due (next_probe_at, partial WHERE kind = 'http' AND paused_at IS NULL).
func (q *Queries) ClaimDueProbes(ctx context.Context, limit int32) ([]Monitor, error) {
	rows, err := q.db.Query(ctx, claimDueProbes, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Monitor{}
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.Slug,
			&i.Name,
			&i.ScheduleKind,
			&i.PeriodS,
			&i.CronExpr,
			&i.Tz,
			&i.GraceS,
			&i.Url,
			&i.Method,
			&i.IntervalS,
			&i.TimeoutS,
			&i.FailThreshold,
			&i.HttpConfig,
			&i.State,
			&i.FailStreak,
			&i.LastCheckinAt,
			&i.NextDeadline,
			&i.NextProbeAt,
			&i.AlertsMuted,
			&i.PausedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createMonitor = `-- name: CreateMonitor :one
INSERT INTO monitors (
    user_id, kind, slug, name,
    schedule_kind, period_s, cron_expr, tz, grace_s,
    url, method, interval_s, timeout_s, fail_threshold, http_config
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    COALESCE(NULLIF($8::text, ''), 'UTC'), $9,
    $10, $11, $12, $13, $14,
    COALESCE($15::jsonb, '{}'::jsonb)
)
RETURNING id, user_id, kind, slug, name, schedule_kind, period_s, cron_expr, tz, grace_s, url, method, interval_s, timeout_s, fail_threshold, http_config, state, fail_streak, last_checkin_at, next_deadline, next_probe_at, alerts_muted, paused_at, created_at, updated_at
`

type CreateMonitorParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	Kind          string      `json:"kind"`
	Slug          string      `json:"slug"`
	Name          string      `json:"name"`
	ScheduleKind  pgtype.Text `json:"schedule_kind"`
	PeriodS       pgtype.Int4 `json:"period_s"`
	CronExpr      pgtype.Text `json:"cron_expr"`
	Tz            string      `json:"tz"`
	GraceS        pgtype.Int4 `json:"grace_s"`
	Url           pgtype.Text `json:"url"`
	Method        pgtype.Text `json:"method"`
	IntervalS     pgtype.Int4 `json:"interval_s"`
	TimeoutS      pgtype.Int4 `json:"timeout_s"`
	FailThreshold pgtype.Int4 `json:"fail_threshold"`
	HttpConfig    []byte      `json:"http_config"`
}

func (q *Queries) CreateMonitor(ctx context.Context, arg CreateMonitorParams) (Monitor, error) {
	row := q.db.QueryRow(ctx, createMonitor,
		arg.UserID,
		arg.Kind,
		arg.Slug,
		arg.Name,
		arg.ScheduleKind,
		arg.PeriodS,
		arg.CronExpr,
		arg.Tz,
		arg.GraceS,
		arg.Url,
		arg.Method,
		arg.IntervalS,
		arg.TimeoutS,
		arg.FailThreshold,
		arg.HttpConfig,
	)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Slug,
		&i.Name,
		&i.ScheduleKind,
		&i.PeriodS,
		&i.CronExpr,
		&i.Tz,
		&i.GraceS,
		&i.Url,
		&i.Method,
		&i.IntervalS,
		&i.TimeoutS,
		&i.FailThreshold,
		&i.HttpConfig,
		&i.State,
		&i.FailStreak,
		&i.LastCheckinAt,
		&i.NextDeadline,
		&i.NextProbeAt,
		&i.AlertsMuted,
		&i.PausedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMonitor = `-- name: DeleteMonitor :exec
DELETE FROM monitors
WHERE id = $1 AND user_id = $2
`

type DeleteMonitorParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteMonitor(ctx context.Context, arg DeleteMonitorParams) error {
	_, err := q.db.Exec(ctx, deleteMonitor, arg.ID, arg.UserID)
	return err
}

const getMonitorByID = `-- name: GetMonitorByID :one
SELECT id, user_id, kind, slug, name, schedule_kind, period_s, cron_expr, tz, grace_s, url, method, interval_s, timeout_s, fail_threshold, http_config, state, fail_streak, last_checkin_at, next_deadline, next_probe_at, alerts_muted, paused_at, created_at, updated_at FROM monitors
WHERE id = $1
`

func (q *Queries) GetMonitorByID(ctx context.Context, id pgtype.UUID) (Monitor, error) {
	row := q.db.QueryRow(ctx, getMonitorByID, id)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Slug,
		&i.Name,
		&i.ScheduleKind,
		&i.PeriodS,
		&i.CronExpr,
		&i.Tz,
		&i.GraceS,
		&i.Url,
		&i.Method,
		&i.IntervalS,
		&i.TimeoutS,
		&i.FailThreshold,
		&i.HttpConfig,
		&i.State,
		&i.FailStreak,
		&i.LastCheckinAt,
		&i.NextDeadline,
		&i.NextProbeAt,
		&i.AlertsMuted,
		&i.PausedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMonitorBySlug = `-- name: GetMonitorBySlug :one
SELECT id, user_id, kind, slug, name, schedule_kind, period_s, cron_expr, tz, grace_s, url, method, interval_s, timeout_s, fail_threshold, http_config, state, fail_streak, last_checkin_at, next_deadline, next_probe_at, alerts_muted, paused_at, created_at, updated_at FROM monitors
WHERE slug = $1
`

func (q *Queries) GetMonitorBySlug(ctx context.Context, slug string) (Monitor, error) {
	row := q.db.QueryRow(ctx, getMonitorBySlug, slug)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Slug,
		&i.Name,
		&i.ScheduleKind,
		&i.PeriodS,
		&i.CronExpr,
		&i.Tz,
		&i.GraceS,
		&i.Url,
		&i.Method,
		&i.IntervalS,
		&i.TimeoutS,
		&i.FailThreshold,
		&i.HttpConfig,
		&i.State,
		&i.FailStreak,
		&i.LastCheckinAt,
		&i.NextDeadline,
		&i.NextProbeAt,
		&i.AlertsMuted,
		&i.PausedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMonitorsByUser = `-- name: ListMonitorsByUser :many
SELECT id, user_id, kind, slug, name, schedule_kind, period_s, cron_expr, tz, grace_s, url, method, interval_s, timeout_s, fail_threshold, http_config, state, fail_streak, last_checkin_at, next_deadline, next_probe_at, alerts_muted, paused_at, created_at, updated_at FROM monitors
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListMonitorsByUser(ctx context.Context, userID pgtype.UUID) ([]Monitor, error) {
	rows, err := q.db.Query(ctx, listMonitorsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Monitor{}
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.Slug,
			&i.Name,
			&i.ScheduleKind,
			&i.PeriodS,
			&i.CronExpr,
			&i.Tz,
			&i.GraceS,
			&i.Url,
			&i.Method,
			&i.IntervalS,
			&i.TimeoutS,
			&i.FailThreshold,
			&i.HttpConfig,
			&i.State,
			&i.FailStreak,
			&i.LastCheckinAt,
			&i.NextDeadline,
			&i.NextProbeAt,
			&i.AlertsMuted,
			&i.PausedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pauseMonitor = `-- name: PauseMonitor :exec
UPDATE monitors
SET paused_at = now()
WHERE id = $1 AND user_id = $2
`

type PauseMonitorParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) PauseMonitor(ctx context.Context, arg PauseMonitorParams) error {
	_, err := q.db.Exec(ctx, pauseMonitor, arg.ID, arg.UserID)
	return err
}

const resumeMonitor = `-- name: ResumeMonitor :exec
UPDATE monitors
SET paused_at = NULL
WHERE id = $1 AND user_id = $2
`

type ResumeMonitorParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) ResumeMonitor(ctx context.Context, arg ResumeMonitorParams) error {
	_, err := q.db.Exec(ctx, resumeMonitor, arg.ID, arg.UserID)
	return err
}
