// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// ClaimDueAlerts is the alerter worker's scan (PING-012): it claims pending
	// outbox rows that are due, locking each so a second replica skips it, and joins
	// everything one send needs — recipient, monitor identity/state/mute flag, and
	// the triggering event — in a single round-trip. FOR UPDATE OF a locks only the
	// alerts row (not the joined monitors/users/events), and SKIP LOCKED lets other
	// workers claim different rows concurrently. Uses idx_alerts_pending
	// (next_attempt_at) WHERE status = 'pending'.
	ClaimDueAlerts(ctx context.Context, arg ClaimDueAlertsParams) ([]ClaimDueAlertsRow, error)
	// Worker scan #1: scheduler claims heartbeat monitors past their deadline.
	// Uses idx_monitors_due (next_deadline, partial WHERE state IN ('up','late') AND paused_at IS NULL).
	// The evaluation clock is passed in (sqlc.arg(now)) rather than SQL now() so the
	// claim and the in-Go transition math share one consistent instant, and tests
	// can drive it deterministically. Production passes time.Now().
	ClaimDueMonitors(ctx context.Context, arg ClaimDueMonitorsParams) ([]Monitor, error)
	// Worker scan #2: prober claims http monitors due for their next probe.
	// Uses idx_monitors_probe_due (next_probe_at, partial WHERE kind = 'http' AND paused_at IS NULL).
	ClaimDueProbes(ctx context.Context, limit int32) ([]Monitor, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateMonitor(ctx context.Context, arg CreateMonitorParams) (Monitor, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredRefreshTokens(ctx context.Context) error
	// :execrows (not :exec) so the store layer can tell "deleted" apart from
	// "no matching row" (foreign or already-deleted id) via RowsAffected.
	DeleteMonitor(ctx context.Context, arg DeleteMonitorParams) (int64, error)
	// EnqueueDownReminders inserts a fresh pending reminder alert for every monitor
	// that is still down, not muted, and has an enabled reminder cadence whose most
	// recent alert (down or prior reminder) is older than that cadence. It reuses
	// the monitor's latest 'down' event as the alert's event_id so the reminder ties
	// back to the outage. The NOT EXISTS guard prevents piling up duplicate pending
	// reminders when the alerter is behind. Returns the inserted rows so the worker
	// can log how many reminders it queued.
	EnqueueDownReminders(ctx context.Context, now pgtype.Timestamptz) ([]Alert, error)
	GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error)
	GetMonitorByID(ctx context.Context, id pgtype.UUID) (Monitor, error)
	GetMonitorBySlug(ctx context.Context, slug string) (Monitor, error)
	// Ingest fast path (PING-008): fetch the monitor and lock its row for the rest
	// of the transaction. Plain FOR UPDATE (block, don't skip) — every ping must be
	// processed, and the lock serializes concurrent pings on the same slug so the
	// read-state / transition / write is atomic (no duplicate recovery/down rows).
	GetMonitorBySlugForUpdate(ctx context.Context, slug string) (Monitor, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	// Outbox row for an alerting transition (PING-009/011). status defaults
	// 'pending' and next_attempt_at defaults now(): the ingest/scheduler fast paths
	// only enqueue, they never dispatch. channel is the sentinel 'default' until a
	// future ticket introduces real notification channels and fans a transition out
	// across them.
	InsertAlert(ctx context.Context, arg InsertAlertParams) (Alert, error)
	// Ingest fast path (PING-008): every ping records exactly one checkin row.
	// source_ip (INET) / user_agent / body are nullable; the store passes NULL
	// when absent. body is already truncated to 10 KB by the server handler.
	InsertCheckin(ctx context.Context, arg InsertCheckinParams) (Checkin, error)
	// Timeline events for a monitor (state transitions, config changes, etc.).
	// meta defaults to an empty object when the caller passes NULL.
	InsertEvent(ctx context.Context, arg InsertEventParams) (Event, error)
	// LatestDownEventBefore finds the most recent 'down' event for a monitor at or
	// before a given time — the start of the current outage. The alerter uses it to
	// compute recovery downtime ("recovered after 42m") for an 'up' alert.
	LatestDownEventBefore(ctx context.Context, arg LatestDownEventBeforeParams) (Event, error)
	ListAPIKeysByUser(ctx context.Context, userID pgtype.UUID) ([]ApiKey, error)
	// Check-in log (PING-014): one monitor's check-ins, newest first. Ownership
	// is checked in the handler, so this filters by monitor_id only (plus an
	// optional cursor). Uses idx_checkins_monitor (monitor_id, created_at DESC).
	// Cursor is the BIGSERIAL id (monotonic), so id < cursor paginates strictly,
	// matching ListEventsByMonitorPage's convention.
	ListCheckinsByMonitorPage(ctx context.Context, arg ListCheckinsByMonitorPageParams) ([]Checkin, error)
	// Dashboard uptime bar (PING-013): last-N-days rollups for a batch of
	// monitors in one query (avoids N+1 across a list page). Table is written by
	// the nightly rollup job (PING-020, not yet built) — until then this always
	// returns zero rows, which callers must treat as "no data yet", not an error.
	ListDailyStatsByMonitorIDs(ctx context.Context, arg ListDailyStatsByMonitorIDsParams) ([]DailyStat, error)
	// Per-monitor event feed (PING-010): ownership is checked in the handler, so
	// this filters by monitor_id only (plus optional type + cursor). Uses
	// idx_events_monitor (monitor_id, created_at DESC).
	ListEventsByMonitorPage(ctx context.Context, arg ListEventsByMonitorPageParams) ([]Event, error)
	// Global event feed (PING-010): the caller's events across all their monitors,
	// newest first, with optional monitor and type filters. Cursor is the BIGSERIAL
	// id (monotonic), so id < cursor paginates strictly. Ordering by id DESC uses
	// idx_events_id.
	ListEventsByUserPage(ctx context.Context, arg ListEventsByUserPageParams) ([]Event, error)
	ListMonitorsByUser(ctx context.Context, userID pgtype.UUID) ([]Monitor, error)
	// Cursor pagination on (created_at, id) rather than OFFSET: created_at alone
	// isn't unique, so the composite key keeps page boundaries stable under
	// concurrent inserts. sqlc.narg(cursor_created_at)/sqlc.narg(cursor_id) are
	// both NULL on the first page (no WHERE filter applied).
	//
	// search/kind/display_state (PING-013) are all sqlc.narg: NULL means "no
	// filter". display_state isn't a real column (it's derived from paused_at in
	// store/monitor.go's toMonitor), so the filter clause replicates that
	// derivation inline rather than comparing against the raw state column — a
	// paused monitor must not surface under its frozen pre-pause state.
	ListMonitorsByUserPage(ctx context.Context, arg ListMonitorsByUserPageParams) ([]Monitor, error)
	// MarkAlertFailed terminally fails an alert (retries exhausted or a permanent
	// delivery error). The alerter also writes an 'alert_failed' event in the same
	// transaction so the failure is visible on the monitor's timeline.
	MarkAlertFailed(ctx context.Context, id int64) error
	// MarkAlertSent finalizes a delivered alert. attempts is bumped so it reflects
	// the total number of send tries including the successful one.
	MarkAlertSent(ctx context.Context, id int64) error
	// Scheduler late->down (PING-009): clear the deadline and bump the fail streak.
	// paused_at untouched (see MarkMonitorLate).
	MarkMonitorDown(ctx context.Context, id pgtype.UUID) error
	// Scheduler up->late (PING-009): re-arm next_deadline to the DOWN threshold
	// (occurrence + grace, computed by the caller) and flip state. paused_at is
	// deliberately untouched — the scheduler must never resume a paused monitor
	// (unlike UpdateMonitorOnCheckin, which auto-resumes on a real check-in).
	MarkMonitorLate(ctx context.Context, arg MarkMonitorLateParams) error
	MuteMonitor(ctx context.Context, arg MuteMonitorParams) (Monitor, error)
	// Pause (PING-010): set the flag only — state is deliberately untouched (paused
	// is a flag, not a state, per §2.3). RETURNING so the handler can echo the
	// updated monitor. Zero rows affected (foreign/missing id) => ErrNotFound.
	PauseMonitor(ctx context.Context, arg PauseMonitorParams) (Monitor, error)
	// RescheduleAlert backs a failed-but-retryable alert off to a later attempt.
	// attempts is bumped and next_attempt_at moved forward; the row stays 'pending'
	// so the next due scan re-claims it.
	RescheduleAlert(ctx context.Context, arg RescheduleAlertParams) error
	// Resume (PING-010): a clean restart — clear the flag, set state='up', and
	// re-arm next_deadline from the resume moment (computed by the caller via
	// nextDeadlineFor; NULL for non-heartbeat / unscheduled). Re-arming from now is
	// what stops a monitor paused past its deadline from tripping late/down the
	// instant it resumes (AC-2).
	ResumeMonitor(ctx context.Context, arg ResumeMonitorParams) (Monitor, error)
	RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (int64, error)
	RevokeRefreshTokenFamily(ctx context.Context, familyID pgtype.UUID) error
	// Atomically marks a token rotated only if it hasn't already been rotated or
	// revoked, closing the check-then-write race between GetRefreshTokenByHash
	// and the rotation write: two concurrent requests replaying the same token
	// can no longer both succeed, since only one UPDATE can match the WHERE
	// clause before rotated_at becomes non-null.
	RotateRefreshTokenIfUnrotated(ctx context.Context, id pgtype.UUID) (RefreshToken, error)
	// SuppressAlert resolves an alert that must not be delivered (monitor muted)
	// without sending it. It reuses the terminal 'sent' status so the row leaves the
	// pending outbox and is never retried; sent_at stays NULL to distinguish a
	// suppressed alert from a delivered one. The transition/event was already
	// recorded upstream, so no notification is owed.
	SuppressAlert(ctx context.Context, id int64) error
	TouchAPIKeyLastUsed(ctx context.Context, id pgtype.UUID) error
	UnmuteMonitor(ctx context.Context, arg UnmuteMonitorParams) (Monitor, error)
	// Partial update: sqlc.narg fields left NULL keep their current value via
	// COALESCE. Ownership-enforced by the id + user_id WHERE, matching
	// Pause/Resume/Delete — a foreign monitor_id updates zero rows rather than
	// erroring, so the store layer must check RowsAffected/pgx.ErrNoRows.
	UpdateMonitor(ctx context.Context, arg UpdateMonitorParams) (Monitor, error)
	// Ingest fast path (PING-008): apply a check-in's effect to the monitor row we
	// already hold locked via GetMonitorBySlugForUpdate. next_deadline is NULL on a
	// fail; paused_at is always cleared (any check-in auto-resumes the monitor).
	// paused_at is cleared (auto-resume) only when the monitor's auto_resume flag is
	// set (PING-010). With auto_resume=false a check-in still records state and
	// re-arms next_deadline, but leaves paused_at set — the scheduler keeps skipping
	// it (its claims filter paused_at IS NULL), so the future deadline is inert
	// until the monitor is explicitly resumed.
	UpdateMonitorOnCheckin(ctx context.Context, arg UpdateMonitorOnCheckinParams) error
}

var _ Querier = (*Queries)(nil)
