// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Worker scan #1: scheduler claims heartbeat monitors past their deadline.
	// Uses idx_monitors_due (next_deadline, partial WHERE state IN ('up','late') AND paused_at IS NULL).
	ClaimDueMonitors(ctx context.Context, limit int32) ([]Monitor, error)
	// Worker scan #2: prober claims http monitors due for their next probe.
	// Uses idx_monitors_probe_due (next_probe_at, partial WHERE kind = 'http' AND paused_at IS NULL).
	ClaimDueProbes(ctx context.Context, limit int32) ([]Monitor, error)
	// Worker scan #3: alerter claims pending outbox rows ready for (re)send.
	// Uses idx_alerts_pending (next_attempt_at, partial WHERE status = 'pending').
	ClaimPendingAlerts(ctx context.Context, limit int32) ([]Alert, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateMonitor(ctx context.Context, arg CreateMonitorParams) (Monitor, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteMonitor(ctx context.Context, arg DeleteMonitorParams) error
	GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error)
	GetMonitorByID(ctx context.Context, id pgtype.UUID) (Monitor, error)
	GetMonitorBySlug(ctx context.Context, slug string) (Monitor, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	ListAPIKeysByUser(ctx context.Context, userID pgtype.UUID) ([]ApiKey, error)
	ListMonitorsByUser(ctx context.Context, userID pgtype.UUID) ([]Monitor, error)
	PauseMonitor(ctx context.Context, arg PauseMonitorParams) error
	ResumeMonitor(ctx context.Context, arg ResumeMonitorParams) error
	RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) error
	TouchAPIKeyLastUsed(ctx context.Context, id pgtype.UUID) error
}

var _ Querier = (*Queries)(nil)
