// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Worker scan #1: scheduler claims heartbeat monitors past their deadline.
	// Uses idx_monitors_due (next_deadline, partial WHERE state IN ('up','late') AND paused_at IS NULL).
	ClaimDueMonitors(ctx context.Context, limit int32) ([]Monitor, error)
	// Worker scan #2: prober claims http monitors due for their next probe.
	// Uses idx_monitors_probe_due (next_probe_at, partial WHERE kind = 'http' AND paused_at IS NULL).
	ClaimDueProbes(ctx context.Context, limit int32) ([]Monitor, error)
	// Worker scan #3: alerter claims pending outbox rows ready for (re)send.
	// Uses idx_alerts_pending (next_attempt_at, partial WHERE status = 'pending').
	ClaimPendingAlerts(ctx context.Context, limit int32) ([]Alert, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateMonitor(ctx context.Context, arg CreateMonitorParams) (Monitor, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredRefreshTokens(ctx context.Context) error
	// :execrows (not :exec) so the store layer can tell "deleted" apart from
	// "no matching row" (foreign or already-deleted id) via RowsAffected.
	DeleteMonitor(ctx context.Context, arg DeleteMonitorParams) (int64, error)
	GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error)
	GetMonitorByID(ctx context.Context, id pgtype.UUID) (Monitor, error)
	GetMonitorBySlug(ctx context.Context, slug string) (Monitor, error)
	// Ingest fast path (PING-008): fetch the monitor and lock its row for the rest
	// of the transaction. Plain FOR UPDATE (block, don't skip) — every ping must be
	// processed, and the lock serializes concurrent pings on the same slug so the
	// read-state / transition / write is atomic (no duplicate recovery/down rows).
	GetMonitorBySlugForUpdate(ctx context.Context, slug string) (Monitor, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	// Outbox row for the alerter worker (PING-012). status defaults 'pending' and
	// next_attempt_at defaults now(): the ingest fast path only enqueues, it never
	// dispatches. channel is the sentinel 'default' until PING-012 introduces real
	// notification channels and fans a transition out across them.
	InsertAlert(ctx context.Context, arg InsertAlertParams) (Alert, error)
	// Ingest fast path (PING-008): every ping records exactly one checkin row.
	// source_ip (INET) / user_agent / body are nullable; the store passes NULL
	// when absent. body is already truncated to 10 KB by the server handler.
	InsertCheckin(ctx context.Context, arg InsertCheckinParams) (Checkin, error)
	// Timeline events for a monitor (state transitions, config changes, etc.).
	// meta defaults to an empty object when the caller passes NULL.
	InsertEvent(ctx context.Context, arg InsertEventParams) (Event, error)
	ListAPIKeysByUser(ctx context.Context, userID pgtype.UUID) ([]ApiKey, error)
	ListMonitorsByUser(ctx context.Context, userID pgtype.UUID) ([]Monitor, error)
	// Cursor pagination on (created_at, id) rather than OFFSET: created_at alone
	// isn't unique, so the composite key keeps page boundaries stable under
	// concurrent inserts. sqlc.narg(cursor_created_at)/sqlc.narg(cursor_id) are
	// both NULL on the first page (no WHERE filter applied).
	ListMonitorsByUserPage(ctx context.Context, arg ListMonitorsByUserPageParams) ([]Monitor, error)
	PauseMonitor(ctx context.Context, arg PauseMonitorParams) error
	ResumeMonitor(ctx context.Context, arg ResumeMonitorParams) error
	RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) error
	RevokeRefreshTokenFamily(ctx context.Context, familyID pgtype.UUID) error
	// Atomically marks a token rotated only if it hasn't already been rotated or
	// revoked, closing the check-then-write race between GetRefreshTokenByHash
	// and the rotation write: two concurrent requests replaying the same token
	// can no longer both succeed, since only one UPDATE can match the WHERE
	// clause before rotated_at becomes non-null.
	RotateRefreshTokenIfUnrotated(ctx context.Context, id pgtype.UUID) (RefreshToken, error)
	TouchAPIKeyLastUsed(ctx context.Context, id pgtype.UUID) error
	// Partial update: sqlc.narg fields left NULL keep their current value via
	// COALESCE. Ownership-enforced by the id + user_id WHERE, matching
	// Pause/Resume/Delete — a foreign monitor_id updates zero rows rather than
	// erroring, so the store layer must check RowsAffected/pgx.ErrNoRows.
	UpdateMonitor(ctx context.Context, arg UpdateMonitorParams) (Monitor, error)
	// Ingest fast path (PING-008): apply a check-in's effect to the monitor row we
	// already hold locked via GetMonitorBySlugForUpdate. next_deadline is NULL on a
	// fail; paused_at is always cleared (any check-in auto-resumes the monitor).
	UpdateMonitorOnCheckin(ctx context.Context, arg UpdateMonitorOnCheckinParams) error
}

var _ Querier = (*Queries)(nil)
